### ISSUE TITLE
is ye reading her github issue reports?

### ISSUE THREAD

**Issue by timm** [ai-se/cocreport#26]
if yes.. please add a smile to this issue report

**Comment by yy2111** [comment]
yes:))

**Comment by timm** [comment]
very good. please don't edit the latex source in the github repo. if you want to work the words, please goto the sharelatex site. 

on the other hand, if you want to leave the latex-ing to me, i would not argue

**Comment by yy2111** [comment]
Sounds good. This week is not good for me, will work on editing it next week. Also here is Barry's reply:

"The coc05 data is still under NDAs. it’s getting harder to even get NDAs from some of the companies.  One of our criteria for COCOMO III and COSYSMO 3.0 is ease of use of data such as coc05."

Btw, any chance you looked at the revised Special issue proposal? 

Thanks,

Ye

**Comment by timm** [comment]
FSE paper due friday. after that?

**Comment by yy2111** [comment]
OK.

Thanks,
Ye
