### ISSUE TITLE
need spreadsheet help

### ISSUE THREAD

**Issue by timm** [ai-se/cocreport#37]
@bigfatnoob can you edit cocreport/extrapolation.xlsx and add "effort" and "KLOC" to the y and x axis of the chart? excel has defeated this old man

**Comment by timm** [comment]
here's the fig, sans axis labels

![image](https://cloud.githubusercontent.com/assets/29195/14061024/c554beb0-f34b-11e5-9d58-6a5c10c1ac14.png)

**Comment by bigfatnoob** [comment]
@timm Pushed to repo. Checkout and the axis titles should be found in extrapoloation.xlsx

**Comment by timm** [comment]
thanks
