### ISSUE TITLE
adding stuff back in

### ISSUE THREAD

**Issue by timm** [ai-se/cocreport#38]
section 4.2 needs peeker and teak as examples of state of the art methods representing progress since COCOMO. 

so that means adding back content into 3.2 and 4.2 (including the 4.2 results)

sorry man

but don't do it know... i've still got the paper on my local hard drive.

**Comment by timm** [comment]
i've added the materia into 3.2

now you have to add quartile charts into 4.2

**Comment by bigfatnoob** [comment]
Done this. Do check this out and let me know if it requires any other changes
