### ISSUE TITLE
next steps

### ISSUE THREAD

**Issue by timm** [ai-se/cocreport#39]
the files are back in sharelatex now. have at them sir.
- [ ] many foornotes and "george!" written over them. please review and then then lets talk about your next steps
- [ ] i need to find the overlap coc2 and nasa93. ye is chasing that
- [ ] george and tim need to walk over the content looking for issues.

**Comment by bigfatnoob** [comment]
Addressed most of the issues with GEORGE on it. We need to fix the typo in figure 2.

**Comment by timm** [comment]
My reports no overlap nasa93 Co 2. Must add that.
